# mysql
mysql:
  username: root
  password: 123456
  ipaddress: 127.0.0.1
  port: 3309
  dbname: douyin

# redis
redis:
  ipaddress: 127.0.0.1
  port: 6379
  authpassword: 123456
  maxidle: 5              #连接池最大空闲数
  maxactive: 0            #连接池最大连接数 0 表示不设上

# resource(静态图片和视频的资源)
resouece:
  ipaddress: 172.20.10.4
  port: 12345